appOptions:
  logLevel: off
  useAi: false
  aiModel: gpt-4o-mini
  aiTemperature: 0.1

hassOptions:
  wsUrl: ws://localhost:8123/api/websocket
  restUrl: http://localhost:8123
  token: test_token
  maxRetries: 1
  retryDelayMs: 100
  stateCheckInterval: 300000

hvacOptions:
  tempSensor: sensor.indoor_temp
  outdoorSensor: sensor.outdoor_temp
  systemMode: auto
  hvacEntities:
    - entityId: climate.test
      enabled: true
      defrost: false
  heating:
    temperature: 21.0
    presetMode: comfort
    temperatureThresholds:
      indoorMin: 19.0
      indoorMax: 22.0
      outdoorMin: -15.0
      outdoorMax: 45.0
  cooling:
    temperature: 25.0
    presetMode: comfort
    temperatureThresholds:
      indoorMin: 23.0
      indoorMax: 28.0
      outdoorMin: -15.0
      outdoorMax: 45.0