# HAG HVAC Configuration for Unit Tests
# Simple configuration without environment variables for testing

appOptions:
  logLevel: "error" # Minimize log noise in tests
  useAi: false
  aiModel: "gpt-4o-mini"
  aiTemperature: 0.1

hassOptions:
  wsUrl: "ws://localhost:8123/api/websocket"
  restUrl: "http://localhost:8123"
  token: "test_token"
  maxRetries: 1
  retryDelayMs: 100
  stateCheckInterval: 300000

hvacOptions:
  tempSensor: "sensor.indoor_temp"
  outdoorSensor: "sensor.outdoor_temp"
  systemMode: "auto"

  hvacEntities:
    - entityId: "climate.test"
      enabled: true
      defrost: false

  heating:
    temperature: 21.5
    presetMode: "wind_free_sleep"
    temperatureThresholds:
      indoorMin: 21.2
      indoorMax: 21.8
      outdoorMin: -5.0
      outdoorMax: 15.0

  cooling:
    temperature: 24.3
    presetMode: "wind_free"
    temperatureThresholds:
      indoorMin: 24
      indoorMax: 24.5
      outdoorMin: 23
      outdoorMax: 55.0

  evaluationCacheMs: 100
