# HAG HVAC Configuration - Fast Test Version
# Optimized for quick startup testing

appOptions:
  logLevel: "debug"
  useAi: false
  aiModel: "gpt-3.5-turbo"
  aiTemperature: 0.1

hassOptions:
  wsUrl: "ws://192.168.0.204:8123/api/websocket"
  restUrl: "http://192.168.0.204:8123/api"
  token: "${HASS_HassOptions__Token}"
  maxRetries: 2          # Reduced from 5 to 2
  retryDelayMs: 500      # Reduced from 1000ms to 500ms
  stateCheckInterval: 300000

hvacOptions:
  tempSensor: "sensor.1st_floor_hall_multisensor_temperature"
  outdoorSensor: "sensor.openweathermap_temperature"
  systemMode: "auto"

  hvacEntities:
    - entityId: "climate.living_room_ac"
      enabled: true
      defrost: true
    - entityId: "climate.bedroom_ac"
      enabled: false
      defrost: false
    - entityId: "climate.matej_ac"
      enabled: false
      defrost: false
    - entityId: "climate.anicka_ac"
      enabled: false
      defrost: false
    - entityId: "climate.radek_ac"
      enabled: false
      defrost: false

  heating:
    temperature: 21.0
    presetMode: "windFreeSleep"
    temperatureThresholds:
      indoorMin: 19.7
      indoorMax: 20.2
      outdoorMin: -5.0
      outdoorMax: 15.0
    defrost:
      enabled: true
      intervalHours: 2
      durationMinutes: 5
      temperatureThreshold: 0.0
      periodSeconds: 7200
      durationSeconds: 300

  cooling:
    temperature: 24.0
    presetMode: "windFree"
    temperatureThresholds:
      indoorMin: 23.5
      indoorMax: 24.0
      outdoorMin: 10.0
      outdoorMax: 45.0

  activeHours:
    start: 5
    startWeekday: 5
    end: 23