# AI-Enhanced HVAC Configuration for Experimental Testing
# This configuration enables AI-powered decision making with LangGraph

appOptions:
  logLevel: debug
  useAi: true
  aiModel: 'gpt-4o-mini'
  aiTemperature: 0.3
  openaiApiKey: '${OPENAI_API_KEY}'
  experimentalFeatures:
    - 'langgraph-state-machine'
    - 'ai-decision-engine'

hassOptions:
  wsUrl: 'ws://localhost:8123/api/websocket'
  restUrl: 'http://localhost:8123/api'
  token: 'your_long_lived_access_token_here'
  maxRetries: 3
  retryDelayMs: 2000
  stateCheckInterval: 60000

hvacOptions:
  tempSensor: 'sensor.hall_multisensor_temperature'
  outdoorSensor: 'sensor.openweathermap_temperature'
  systemMode: 'auto'

  hvacEntities:
    - entityId: 'climate.heating'
      enabled: true
      defrost: false
    - entityId: 'climate.cooling'
      enabled: true
      defrost: false

  heating:
    temperature: 21.0
    presetMode: 'comfort'
    temperatureThresholds:
      indoorMin: 18.0
      indoorMax: 24.0
      outdoorMin: -20.0
      outdoorMax: 15.0
    defrost:
      temperatureThreshold: 0.0
      periodSeconds: 3600
      durationSeconds: 300

  cooling:
    temperature: 24.0
    presetMode: 'eco'
    temperatureThresholds:
      indoorMin: 20.0
      indoorMax: 28.0
      outdoorMin: 20.0
      outdoorMax: 45.0

  activeHours:
    start: 7
    startWeekday: 6
    end: 23
