# HAG HVAC Configuration - Production
# Production configuration with optimized settings for reliability and efficiency

appOptions:
  logLevel: "info"
  useAi: false
  aiModel: "gpt-3.5-turbo"
  aiTemperature: 0.1

hassOptions:
  wsUrl: "ws://192.168.0.204:8123/api/websocket"
  restUrl: "http://192.168.0.204:8123/api"
  token: "${HASS_HassOptions__Token}"
  maxRetries: 1000
  retryDelayMs: 5000
  stateCheckInterval: 300000

hvacOptions:
  tempSensor: "sensor.1st_floor_hall_multisensor_temperature"
  outdoorSensor: "sensor.openweathermap_temperature"
  systemMode: "auto"

  hvacEntities:
    - entityId: "climate.living_room_ac"
      enabled: true
      defrost: true
    - entityId: "climate.bedroom_ac"
      enabled: false
      defrost: false
    - entityId: "climate.matej_ac"
      enabled: false
      defrost: false
    - entityId: "climate.anicka_ac"
      enabled: false
      defrost: false
    - entityId: "climate.radek_ac"
      enabled: true
      defrost: false

  heating:
    temperature: 21.5
    presetMode: "wind_free_sleep"
    temperatureThresholds:
      indoorMin: 21.2
      indoorMax: 21.8
      outdoorMin: -5.0
      outdoorMax: 15.0
    defrost:
      enabled: true
      intervalHours: 2
      durationMinutes: 5
      temperatureThreshold: 0.0
      periodSeconds: 7200 # 2 hours
      durationSeconds: 300 # 5 minutes

  cooling:
    temperature: 24.3
    presetMode: "wind_free"
    temperatureThresholds:
      indoorMin: 24
      indoorMax: 24.5
      outdoorMin: 23
      outdoorMax: 55.0

  activeHours:
    start: 9
    startWeekday: 9 # Weekday start
    end: 20

  evaluationCacheMs: 100 # Cache evaluations for 100ms
