# HAG HVAC Configuration
# Direct port from Python configuration with TypeScript-specific enhancements

appOptions:
  logLevel: "debug" # debug, info, warn, error, critical
  useAi: false # Enable AI agent for intelligent decisions
  aiModel: "gpt-3.5-turbo" # AI model to use
  aiTemperature: 0.1 # AI model temperature

hassOptions:
  # wsUrl: "ws://192.168.0.204:8123/api/websocket"
  wsUrl: wss://94mzt2ecyq0sud43fdto7supfzisp1y8.ui.nabu.casa/api/websocket
  # restUrl: "http://192.168.0.204:8123/api"
  restUrl: https://94mzt2ecyq0sud43fdto7supfzisp1y8.ui.nabu.casa/api
  token: "${HASS_HassOptions__Token}" # Environment variable for security
  maxRetries: 5
  retryDelayMs: 1000
  stateCheckInterval: 300000

hvacOptions:
  tempSensor: "sensor.1st_floor_hall_multisensor_temperature"
  outdoorSensor: "sensor.openweathermap_temperature"
  systemMode: "auto" # auto, heat_only, cool_only, off

  hvacEntities:
    - entityId: "climate.living_room_ac"
      enabled: true
      defrost: true
    - entityId: "climate.bedroom_ac"
      enabled: false
      defrost: false
    - entityId: "climate.matej_ac"
      enabled: false
      defrost: false
    - entityId: "climate.anicka_ac"
      enabled: false
      defrost: false
    - entityId: "climate.radek_ac"
      enabled: false
      defrost: false

  heating:
    temperature: 21.0
    presetMode: "wind_free"
    temperatureThresholds:
      indoorMin: 20.50
      indoorMax: 22.50
      outdoorMin: -5.0
      outdoorMax: 15.0
    defrost:
      enabled: true
      intervalHours: 2
      durationMinutes: 5
      temperatureThreshold: 0.0
      periodSeconds: 7200
      durationSeconds: 300

  cooling:
    temperature: 24.5
    presetMode: "wind_free"
    temperatureThresholds:
      indoorMin: 23.5
      indoorMax: 26.0
      outdoorMin: 10.0
      outdoorMax: 45.0

  activeHours:
    start: 6
    startWeekday: 6
    end: 23

  evaluationCacheMs: 100
